# Generated by Django 3.2.6 on 2021-08-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210816_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seen_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
